# Generated by Django 5.2.17 on 2026-09-23 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PutHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('put_type', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], max_length=10, verbose_name='PUT種別')),
                ('patient_id', models.CharField(max_length=20, verbose_name='患者ID')),
                ('patient_name', models.CharField(max_length=50, verbose_name='患者氏名')),
                ('patient_name_kana', models.CharField(max_length=50, verbose_name='患者氏名カナ')),
                ('admission_id', models.CharField(max_length=20, verbose_name='入院ID')),
                ('request_data', models.JSONField(verbose_name='送信データ')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='ステータスコード')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='レスポンス')),
                ('is_success', models.BooleanField(default=False, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー内容')),
                ('put_at', models.DateTimeField(auto_now_add=True, verbose_name='PUT日時')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.bed', verbose_name='ベッド番号')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='put_histories', to='masters.room', verbose_name='病室')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.ward', verbose_name='病棟')),
            ],
            options={
                'verbose_name': 'PUT履歴',
                'verbose_name_plural': 'PUT履歴',
                'ordering': ['-put_at'],
            },
        ),
    ]
