# Generated by Django 5.2.17 on 2026-09-26 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
        ('masters', '0002_remove_room_is_price_difference_room_is_private_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puthistory',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='puthistory',
            name='room',
        ),
        migrations.RemoveField(
            model_name='puthistory',
            name='ward',
        ),
        migrations.CreateModel(
            name='StayHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_id', models.CharField(max_length=20, verbose_name='入院ID')),
                ('stayed_at', models.DateTimeField(verbose_name='滞在日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.bed', verbose_name='ベッド')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.room', verbose_name='病室')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.ward', verbose_name='病棟')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('admission_id', 'stayed_at'), name='unique_admission_stayed_at')],
            },
        ),
    ]
