# Generated by Django 5.2.17 on 2026-09-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_remove_puthistory_bed_remove_puthistory_room_and_more'),
        ('masters', '0003_persresponsemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puthistory',
            name='is_success',
        ),
        migrations.AddField(
            model_name='puthistory',
            name='is_communication_success',
            field=models.BooleanField(default=False, verbose_name='通信成功'),
        ),
        migrations.AddField(
            model_name='puthistory',
            name='is_integration_success',
            field=models.BooleanField(default=False, verbose_name='連携成功'),
        ),
        migrations.AddField(
            model_name='puthistory',
            name='is_put_target',
            field=models.BooleanField(default=True, verbose_name='PUT対象'),
        ),
        migrations.AddField(
            model_name='puthistory',
            name='pers_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.persresponsemaster', verbose_name='PERSレスポンス'),
        ),
        migrations.AlterField(
            model_name='puthistory',
            name='admission_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='入院ID'),
        ),
        migrations.AlterField(
            model_name='puthistory',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='送信データ'),
        ),
    ]
