# Generated by Django 5.2.17 on 2026-09-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emr_id', models.CharField(max_length=10, verbose_name='電カルID')),
                ('name', models.CharField(max_length=10, verbose_name='病室')),
                ('is_price_difference', models.BooleanField(default=False, verbose_name='室料差額')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '病室',
                'verbose_name_plural': '病室',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emr_id', models.CharField(max_length=10, verbose_name='電カルID')),
                ('name', models.CharField(max_length=10, verbose_name='病棟名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '病棟',
                'verbose_name_plural': '病棟',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emr_id', models.CharField(max_length=10, verbose_name='電カルID')),
                ('bed_no', models.CharField(max_length=10, verbose_name='ベッド番号')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='masters.room', verbose_name='病室')),
            ],
            options={
                'verbose_name': 'ベッド番号',
                'verbose_name_plural': 'ベッド番号',
                'ordering': ['bed_no'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='masters.ward', verbose_name='病棟'),
        ),
    ]
