# Generated by Django 5.2.17 on 2026-09-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_price_difference',
        ),
        migrations.AddField(
            model_name='room',
            name='is_private_room',
            field=models.BooleanField(default=False, verbose_name='個室'),
        ),
    ]
