# Generated by Django 5.2.17 on 2026-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_room_is_price_difference_room_is_private_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersResponseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveIntegerField(verbose_name='ステータスコード')),
                ('result', models.CharField(blank=True, max_length=30, verbose_name='結果')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(verbose_name='状況')),
                ('action', models.TextField(verbose_name='対応')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('status_code', 'result'), name='unique_pers_response')],
            },
        ),
    ]
